# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SQL-SyntaxModel-SkipID
version:      0.29
version_from: 
installdirs:  site
requires:
    Locale::KeyedText:             0.04
    SQL::SyntaxModel:              0.22

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
